name: Run regresion tests
on:
  push:
    branches: ['main']
  workflow_dispatch:
  pull_request: 
    types: [opened, synchronize, reopened]

jobs:
  regression-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21.1
      - run: go mod download && go test -v ./...
